<?php
    $data=array(
        0=>array(
            'goodsId'=>'1',
            'href'=>'#',
            'src'=>'images/p1.jpg',
            'pic'=>'促销价：￥1449.00元',
            'title'=>'Air Jordan 1 High OG WMNS AJ1 绒毛黑白熊猫 特价',
            'pp'=>'加入购物车',
        ),
        1=>array(
            'goodsId'=>'2',
            'href'=>'#',
            'src'=>'images/p2.jpg',
            'pic'=>'新新价：￥2599.00元',
            'title'=>'Adidas YEEZY 700 椰子700 灰白 米白复古老爹鞋 特价',
            'pp'=>'加入购物车',
        ),
        2=>array(
            'goodsId'=>'3',
            'href'=>'#',
            'src'=>'images/p3.jpg',
            'pic'=>'促销价：￥1599.00元',
            'title'=>'Nike Air Foamposite Pro 哈达威 新铜喷泡 特价',
            'pp'=>'加入购物车',
        ),
        3=>array(
            'goodsId'=>'4',
            'href'=>'#',
            'src'=>'images/p4.jpg',
            'pic'=>'促销价：￥1499.00元',
            'title'=>'现货Air Jordan 1 Crimson Tint AJ1 OG男 黑粉荔枝皮脏粉 特价',
            'pp'=>'加入购物车',
        ),
        4=>array(
            'goodsId'=>'5',
            'href'=>'#',
            'src'=>'images/p5.jpg',
            'pic'=>'促销价：￥999.00元',
            'title'=>'Air Jordan aj14 Retro  经典情侣款 白红 特价',
            'pp'=>'加入购物车',
        ),
        5=>array(
            'goodsId'=>'6',
            'href'=>'#',
            'src'=>'images/p6.jpg',
            'pic'=>'新新价：￥2399.00元',
            'title'=>'Nike x Fear Of God Moccasin 联名 休闲鞋',
            'pp'=>'加入购物车',
        ),
        6=>array(
            'goodsId'=>'7',
            'href'=>'#',
            'src'=>'images/p7.jpg',
            'pic'=>'新新价：￥799.00元',
            'title'=>'NIKE P-6000 2019新款 男女银灰复古气垫缓震跑步鞋',
            'pp'=>'加入购物车',
        ),
        7=>array(
            'goodsId'=>'8',
            'href'=>'#',
            'src'=>'images/p8.jpg',
            'pic'=>'新新价：￥999.00元',
            'title'=>'Nike Kyrie 5 欧文5笑脸炫彩 男子实战篮球鞋',
            'pp'=>'加入购物车',
        ),
        8=>array(
            'goodsId'=>'9',
            'href'=>'#',
            'src'=>'images/d3.jpg',
            'pic'=>'促销价：￥300.00元',
            'title'=>'Supreme 19SS Fruit Tee 水果 香蕉 照片 T恤 特价',
            'pp'=>'加入购物车',
        ),
        9=>array(
            'goodsId'=>'10',
            'href'=>'#',
            'src'=>'images/d4.jpg',
            'pic'=>'新新价：￥218.00元',
            'title'=>'CONKLAB 2019春夏潮牌花卉短袖印花男宽松情侣ins超火半袖',
            'pp'=>'加入购物车',
        ),
        10=>array(
            'goodsId'=>'11',
            'href'=>'#',
            'src'=>'images/d5.jpg',
            'pic'=>'促销价：￥349.00元',
            'title'=>'NIKE 2018年新款女子 W NSW TCH FLC HOODIE FZ 夹克 2折特价',
            'pp'=>'加入购物车',
        ),
        11=>array(
            'goodsId'=>'12',
            'href'=>'#',
            'src'=>'images/d6.jpg',
            'pic'=>'新新价：￥999.00元',
            'title'=>'Supreme 19ss Fruit Tee 水果香蕉照片 x-design 定制款 特价',
            'pp'=>'加入购物车',
        ),
        );
    echo json_encode($data);
    ?>
